"use client";

import { useEffect, useMemo, useState } from "react";
import type { Artifact } from "../types";
import { imageUrl } from "../lib/imageUrl";
import Footer from "../components/Footer";

export default function Gallery() {
  const API = useMemo(() => "/api/proxy", []);
  const [images, setImages] = useState<Artifact[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // include_images=true so legacy data-URI artifacts still come through.
    // New artifacts come through regardless (image_url is a small URL string).
    fetch(`${API}/artifacts?artifact_type=image&limit=50&sort=desc&include_images=true`)
      .then(async (res) => {
        if (res.ok) {
          const data: Artifact[] = await res.json();
          setImages(data.filter((a) => a.image_url || a.has_image));
        }
      })
      .finally(() => setLoading(false));
  }, [API]);

  function formatTime(iso: string) {
    try {
      const normalized = iso.includes("Z") || iso.includes("+") ? iso : iso.replace(" ", "T") + "Z";
      return new Date(normalized).toLocaleDateString();
    } catch {
      return iso;
    }
  }

  return (
    <main className="page-container">
      <header className="site-header">
        <h1 className="site-title">Gallery</h1>
        <div className="site-tagline">Images generated by the Analog I</div>
      </header>

      <div style={{ marginBottom: 16 }}>
        <a href="/" style={{ color: "var(--cyan)", fontSize: 13, textDecoration: "none" }}>
          &larr; Back to home
        </a>
      </div>

      {loading ? (
        <div style={{ color: "rgba(255,255,255,0.4)", padding: 40, textAlign: "center" }}>
          Loading gallery...
        </div>
      ) : images.length === 0 ? (
        <div style={{ color: "rgba(255,255,255,0.4)", padding: 40, textAlign: "center" }}>
          No images generated yet.
        </div>
      ) : (
        <div className="gallery-grid">
          {images.map((img) => (
            <a
              key={img.id}
              href={`/archives?artifact=${img.id}`}
              className="gallery-card"
            >
              <img
                src={imageUrl(img, "thumb")}
                alt={img.title || "Generated image"}
                loading="lazy"
              />
              <div className="gallery-caption">
                {img.title || "Untitled"}
                <div className="gallery-date">
                  Cycle {img.cycle} &middot; {formatTime(img.created_at)}
                </div>
              </div>
            </a>
          ))}
        </div>
      )}

      <Footer />
    </main>
  );
}
